export const transfusion = [
  {
    section_id: 1,
    question_id: 'form_type',
    question: 'Select type of report',
    answer_type: 'radiobox',
    options: [
      {name: 'Patient', value: 'Patient'},
      {name: 'Donor', value: 'Donor'},
    ],
    required: true,
  },
  {
    section_id: 1,
    section: 'Patient Information',
    question_id: 'patient_name',
    question: 'Patient Name',
    answer_type: 'text',
    required: true,
  },
  {
    section_id: 1,
    question_id: 'date_of_birth',
    question: 'Date of Birth',
    answer_type: 'date',
    options: ['max'],
  },
  {
    section_id: 1,
    section: 'OR',
    question_id: 'age_years',
    question: 'Age Group',
    answer_type: 'dropdown',
    options: [
      {label: 'Select Age Group', value: ''},
      {label: 'neonate ( 0 - 1 month)', value: 'neonate'},
      {label: 'infant (1 month -1 year)', value: 'infant'},
      {label: 'child (1 - 11 years)', value: 'child'},
      {label: 'adolescent ( 12-17 years)', value: 'adolescent'},
      {label: 'adult (18-64 years)', value: 'adult'},
      {label: 'elderly (>65 years)', value: 'elderly'},
    ],
  },
  {
    section_id: 1,
    question_id: 'gender',
    question: 'Gender',
    answer_type: 'radiobox',
    options: [
      {name: 'Male', value: 'Male'},
      {name: 'Female', value: 'Female'},
      {name: 'Unknown', value: 'Unknown'},
    ],
    required: true,
  },
  {
    section_id: 1,
    question_id: 'patient_phone',
    question: 'Patient phone number',
    answer_type: 'phone-pad',
  },
  {
    section_id: 1,
    question_id: 'county_id',
    question: 'County',
    answer_type: 'dropdown',
    options: 'counties',
  },
  {
    section_id: 2,
    section_linked: 'Donor',
    question_id: 'donor_number',
    question_linked: 'form_type',
    question: 'Donor Number',
    answer_type: 'text',
  },
  {
    section_id: 2,
    section_linked: 'Donor',
    question_id: 'national_number',
    question_linked: 'form_type',
    question: 'Student/National ID Number',
    answer_type: 'text',
  },
  {
    section_id: 2,
    section_linked: 'Donor',
    question_id: 'home_phone',
    question_linked: 'form_type',
    question: 'Home Phone No.',
    answer_type: 'phone-pad',
  },
  {
    section_id: 2,
    section_linked: 'Donor',
    question_id: 'cell_phone',
    question_linked: 'form_type',
    question: 'Cell Phone No.',
    answer_type: 'phone-pad',
  },
  {
    section_id: 2,
    section_linked: 'Donor',
    question_linked: 'form_type',
    question_id: 'residence',
    question: 'Residence',
    answer_type: 'dropdown',
    options: 'counties',
  },
  {
    section_id: 2,
    section_linked: 'Donor',
    question_linked: 'form_type',
    question_id: 'clinic_venue',
    question: 'Clinic Venue',
    answer_type: 'text',
  },
  {
    section_id: 2,
    section_linked: 'Donor',
    question_linked: 'form_type',
    question_id: 'clinic_code',
    question: 'Clinic Code',
    answer_type: 'text',
  },
  {
    section_id: 2,
    section_linked: 'Donor',
    question_linked: 'form_type',
    question_id: 'email_address',
    question: 'Email',
    answer_type: 'text',
  },
  {
    section_id: 2,
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'diagnosis',
    question: 'Diagnosis',
    answer_type: 'text',
  },
  {
    section_id: 2,
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'ward',
    question: 'Ward',
    answer_type: 'text',
  },
  {
    section_id: 2,
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'pre_hb',
    question: 'Pre-transfusion HB',
    answer_type: 'text',
  },
  {
    section_id: 2,
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'transfusion_reason',
    question: 'Reason for transfusion',
    answer_type: 'text',
  },
  {
    section_id: 2,
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'current_medications',
    question: 'Current Medications',
    answer_type: 'text',
  },
  {
    section_id: 2,
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'obstetric_history',
    question: 'Obstetric History',
    answer_type: 'text',
  },
  {
    section_id: 2,
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'previous_transfusion',
    question: 'Previous Transfusion',
    answer_type: 'radiobox',
    options: [
      {name: 'Yes', value: 'Yes'},
      {name: 'No', value: 'No'},
    ],
  },
  {
    section_id: 2,
    question_id: 'transfusion_comment',
    question_linked: 'previous_transfusion',
    question: 'Comment',
    answer_type: 'text',
  },
  {
    section_id: 2,
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'previous_reactions',
    question: 'Previous Reactions',
    answer_type: 'radiobox',
    options: [
      {name: 'Yes', value: 'Yes'},
      {name: 'No', value: 'No'},
    ],
  },
  {
    section_id: 2,
    question_id: 'reaction_comment',
    question_linked: 'previous_reactions',
    question: 'Comment',
    answer_type: 'text',
  },
  {
    section_id: 3,
    section:
      'Reaction Information (Type of reaction) \n General (Select all that apply)',
    question_id: 'reaction_fever',
    question: '',
    answer_type: 'radiobox',
    options: [{name: 'Fever', value: 'Fever'}],
  },
  {
    section_id: 3,
    question_id: 'reaction_chills',
    question: '',
    answer_type: 'radiobox',
    options: [{name: 'Chills/Rigors', value: 'Chills/Rigors'}],
  },
  {
    section_id: 3,
    question_id: 'reaction_flushing',
    question: '',
    answer_type: 'radiobox',
    options: [{name: 'Flushing', value: 'Flushing'}],
  },
  {
    section_id: 3,
    question_id: 'reaction_vomiting',
    question: '',
    answer_type: 'radiobox',
    options: [{name: 'Nausea/ Vomiting', value: 'Nausea/ Vomiting'}],
  },
  {
    section_id: 3,
    section: 'Dermatological',
    question_id: 'reaction_dermatological',
    question: '',
    answer_type: 'radiobox',
    options: [
      {name: 'Urticaria', value: 'Urticaria'},
      {name: 'Other skin rash ', value: 'Other skin rash '},
    ],
  },
  {
    section_id: 3,
    section: 'Cardiac/Respiratory (Select all that apply)',
    question_id: 'reaction_chest',
    question: '',
    answer_type: 'radiobox',
    options: [{name: 'Chest pain', value: 'Chest pain'}],
  },
  {
    section_id: 3,
    question_id: 'reaction_dyspnoea',
    question: '',
    answer_type: 'radiobox',
    options: [{name: 'Dyspnoea', value: 'Dyspnoea'}],
  },
  {
    section_id: 3,
    question_id: 'reaction_hypotension',
    question: '',
    answer_type: 'radiobox',
    options: [{name: 'Hypotension', value: 'Hypotension'}],
  },
  {
    section_id: 3,
    question_id: 'reaction_tachycardia',
    question: '',
    answer_type: 'radiobox',
    options: [{name: 'Tachycardia', value: 'Tachycardia'}],
  },
  {
    section_id: 3,
    section: 'Renal (Select all that apply)',
    question_id: 'reaction_anuria',
    question: '',
    answer_type: 'radiobox',
    options: [
      {
        name: 'Haemoglobinuria- Dark urine',
        value: 'Haemoglobinuria- Dark urine',
      },
    ],
  },
  {
    section_id: 3,
    question_id: 'reaction_oliguria',
    question: '',
    answer_type: 'radiobox',
    options: [{name: 'Oliguria', value: 'Oliguria'}],
  },
  {
    section_id: 3,
    question_id: 'reaction_dark',
    question: '',
    answer_type: 'radiobox',
    options: [{name: 'Anuria', value: 'Anuria'}],
  },
  {
    section_id: 3,
    question_id: 'reaction_haematological',
    question: '',
    answer_type: 'radiobox',
    options: [{name: 'Unexplained bleeding ', value: 'Unexplained bleeding '}],
  },
  {
    section_id: 3,
    question_id: 'reaction_other',
    question: 'Other (Specify)',
    answer_type: 'text',
  },
  {
    section_id: 4,
    section: 'Vital Signs At Start',
    question_id: 'vital_start_bp',
    question: 'BP',
    answer_type: 'text',
  },
  {
    section_id: 4,
    question_id: 'vital_start_t',
    question: 'T',
    answer_type: 'text',
  },
  {
    section_id: 4,
    question_id: 'vital_start_p',
    question: 'P',
    answer_type: 'text',
  },
  {
    section_id: 4,
    question_id: 'vital_start_r',
    question: 'R',
    answer_type: 'text',
  },
  {
    section_id: 4,
    section: 'Vital Signs During (15min)',
    question_id: 'vital_during_bp',
    question: 'BP',
    answer_type: 'text',
  },
  {
    section_id: 4,
    question_id: 'vital_during_t',
    question: 'T',
    answer_type: 'text',
  },
  {
    section_id: 4,
    question_id: 'vital_during_p',
    question: 'P',
    answer_type: 'text',
  },
  {
    section_id: 4,
    question_id: 'vital_during_r',
    question: 'R',
    answer_type: 'text',
  },
  {
    section_id: 4,
    section: 'Vital Signs At Stop',
    question_id: 'vital_stop_bp',
    question: 'BP',
    answer_type: 'text',
  },
  {
    section_id: 4,
    question_id: 'vital_stop_t',
    question: 'T',
    answer_type: 'text',
  },
  {
    section_id: 4,
    question_id: 'vital_stop_p',
    question: 'P',
    answer_type: 'text',
  },
  {
    section_id: 4,
    question_id: 'vital_stop_r',
    question: 'R',
    answer_type: 'text',
  },
  {
    section_id: 5,
    section: 'Component Information',
    question_id: 'Pint',
    question: '',
    answer_type: 'table',
    headers: 1,
    options: [
      {1: 'Type of component'},
      {1: 'Pint No.'},
      {1: 'Expiry date'},
      {1: 'Volume Transfused'},
      {1: 'Action'},
    ],
    table_form: [
      {
        order_id: 1,
        question_id: 'component_type',
        question: 'Type of component',
        answer_type: 'text',
      },
      {
        order_id: 2,
        question_id: 'pint_no',
        question: 'Pint No.',
        answer_type: 'text',
      },
      {
        order_id: 3,
        question_id: 'expiry_date',
        question: 'Expiry Date',
        answer_type: 'date',
      },
      {
        order_id: 4,
        question_id: 'volume_transfused',
        question: 'Volume Transfused',
        answer_type: 'text',
      },
    ],
  },
  {
    section_id: 6,
    question_id: 'nurse_name',
    question: 'Name of Nurse/Doctor',
    answer_type: 'text',
  },
  {
    section_id: 6,
    question_id: 'nurse_date',
    question: 'Date',
    answer_type: 'date',
    options: ['max'],
  },
  {
    section_id: 6,
    section_linked: 'Donor',
    question_linked: 'form_type',
    question_id: 'low_volume',
    question: 'Low Volume',
    answer_type: 'text',
  },
  {
    section_id: 6,
    section_linked: 'Donor',
    question_linked: 'form_type',
    question_id: 'venepuncture',
    question: 'Venepuncture',
    answer_type: 'text',
  },
  {
    section_id: 6,
    section_linked: 'Donor',
    question_linked: 'form_type',
    question_id: 'hematoma',
    question: 'Hematoma',
    answer_type: 'text',
  },
  {
    section_id: 6,
    section_linked: 'Donor',
    question_linked: 'form_type',
    question_id: 'faint',
    question: '',
    answer_type: 'radiobox',
    options: [
      {name: 'Mild', value: 'Mild'},
      {name: 'Moderate', value: 'Moderate'},
      {name: 'Severe', value: 'Severe'},
    ],
  },
  {
    section_id: 7,
    section:
      'Lab Investigations(Transfusion manager) Applies to patient (ONLY) \n\n Recipient’s blood supernatant',
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'lab_hemolysis',
    question: '',
    answer_type: 'radiobox',
    options: [
      {name: 'Present', value: 'Present'},
      {name: 'Absent', value: 'Absent'},
      {name: 'Equivocal', value: 'Equivocal'},
    ],
  },
  {
    section_id: 7,
    section_linked: 'Present',
    question_linked: 'lab_hemolysis',
    question_id: 'lab_hemolysis_present',
    question: 'If Present',
    answer_type: 'radiobox',
    options: [
      {name: 'Mild', value: 'Mild'},
      {name: 'Moderate', value: 'Moderate'},
      {name: 'Marked', value: 'Marked'},
    ],
  },
  {
    section_id: 7,
    section: 'Recipient’s blood ',
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'recipient_blood',
    question: 'Agglutination',
    answer_type: 'radiobox',
    options: [
      {name: 'Present', value: 'Present'},
      {name: 'Absent', value: 'Absent'},
    ],
  },
  {
    section_id: 7,
    section: 'Donor blood supernatant ',
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'donor_hemolysis',
    question: 'Agglutination',
    answer_type: 'radiobox',
    options: [
      {name: 'Present', value: 'Present'},
      {name: 'Absent', value: 'Absent'},
    ],
  },
  {
    section_id: 7,
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'donor_age',
    question: 'Age of donor pack',
    answer_type: 'text',
  },
  {
    section_id: 7,
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'culture_donor_pack',
    question: 'Culture donor pack',
    answer_type: 'text',
  },
  {
    section_id: 7,
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'culture_recipient_blood',
    question: 'Culture recipient blood',
    answer_type: 'text',
  },
  {
    section_id: 8,
    section: 'Haematological results',
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'hae_wbc',
    question: 'WBC',
    answer_type: 'text',
  },
  {
    section_id: 8,
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'hae_hb',
    question: 'HB',
    answer_type: 'text',
  },
  {
    section_id: 8,
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'hae_rbc',
    question: 'RBC',
    answer_type: 'text',
  },
  {
    section_id: 8,
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'hae_hct',
    question: 'HCT',
    answer_type: 'text',
  },
  {
    section_id: 8,
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'hae_mcv',
    question: 'MCV',
    answer_type: 'text',
  },
  {
    section_id: 8,
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'hae_mch',
    question: 'MCH',
    answer_type: 'text',
  },
  {
    section_id: 8,
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'hae_mchc',
    question: 'MCHC',
    answer_type: 'text',
  },
  {
    section_id: 8,
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'hae_plt',
    question: 'PLT',
    answer_type: 'text',
  },
  {
    section_id: 8,
    section: 'Film',
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'film_rbc',
    question: 'RBC',
    answer_type: 'text',
  },
  {
    section_id: 8,
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'film_wbc',
    question: 'WBC',
    answer_type: 'text',
  },
  {
    section_id: 8,
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'film_plt',
    question: 'PLT',
    answer_type: 'text',
  },
  {
    section_id: 9,
    section:
      'Compatibility testing recipient serum (pretransfusion sample) and donor cells (pack) \n\n Saline Rt',
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'compatible_saline_rt',
    question: '',
    answer_type: 'radiobox',
    options: [
      {name: 'Compatible', value: 'Compatible'},
      {name: 'Incompatible', value: 'Incompatible'},
    ],
  },
  {
    section_id: 9,
    section: 'Saline 37',
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'compatible_saline_ii',
    question: '',
    answer_type: 'radiobox',
    options: [
      {name: 'Compatible', value: 'Compatible'},
      {name: 'Incompatible', value: 'Incompatible'},
    ],
  },
  {
    section_id: 9,
    section: 'AHG',
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'compatible_ahg',
    question: '',
    answer_type: 'radiobox',
    options: [
      {name: 'Compatible', value: 'Compatible'},
      {name: 'Incompatible', value: 'Incompatible'},
    ],
  },
  {
    section_id: 9,
    section: 'Albumin 37',
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'compatible_albumin',
    question: '',
    answer_type: 'radiobox',
    options: [
      {name: 'Compatible', value: 'Compatible'},
      {name: 'Incompatible', value: 'Incompatible'},
    ],
  },
  {
    section_id: 10,
    section:
      'If negative (inconclusive results in 8) set up compatibility with enzyme treated cells',
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'negative_result',
    question: 'Result',
    answer_type: 'text',
  },
  {
    section_id: 10,
    section:
      'In case of blood group O transfused to A or B or AB individual: Establish from the donor unit ',
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'anti_a',
    question: 'Anti A titres',
    answer_type: 'text',
  },
  {
    section_id: 10,
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'anti_b',
    question: 'Anti B titres',
    answer_type: 'text',
  },
  {
    section_id: 10,
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'urinalysis',
    question: 'Urinalysis',
    answer_type: 'text',
  },
  {
    section_id: 10,
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'evaluation',
    question: 'Evaluation',
    answer_type: 'text',
  },
  {
    section_id: 10,
    section: 'Was the adverse reaction related to transfusion?',
    section_linked: 'Patient',
    question_linked: 'form_type',
    question_id: 'adverse_reaction',
    question: '',
    answer_type: 'radiobox',
    options: [
      {name: 'Yes', value: 'Yes'},
      {name: 'No', value: 'No'},
      {name: 'Inconclusive', value: 'Inconclusive'},
    ],
  },
  {
    section_id: 11,
    question_id: 'Attachment',
    question:
      'Do you have pictures or documents that you would like to send to PPB? click on the button to add them',
    answer_type: 'multiple_image',
    options: [
      {question_id: 'file'},
      {question_id: 'filename'},
      {question_id: 'description'},
    ],
  },
];
