export const aefi = [
  {
    section_id: 1,
    question_id: 'name_of_institution',
    question: 'Name of reporting institution',
    answer_type: 'text',
    required: true,
    search: 'institute',
    search_url: 'facility_codes',
  },
  {
    section_id: 1,
    question_id: 'institution_code',
    question: 'Institution MFL Code',
    answer_type: 'text',
    search: 'institute',
    search_url: 'facility_codes',
  },
  {
    section_id: 1,
    question_id: 'county_id',
    question: 'County',
    answer_type: 'dropdown',
    options: 'counties',
    required: true,
  },
  {
    section_id: 1,
    question_id: 'sub_county_id',
    question_linked: 'county_id',
    question: 'Sub County',
    answer_type: 'dropdown',
    options: 'subcounties',
  },
  {
    section_id: 2,
    section: 'Patient Details',
    question_id: 'patient_name',
    question: "Patient's Name",
    answer_type: 'text',
    required: true,
  },
  {
    section_id: 2,
    question_id: 'ip_no',
    question: 'IP/OP NO',
    answer_type: 'text',
  },
  {
    section_id: 2,
    question_id: 'date_of_birth',
    question: 'Date of Birth',
    answer_type: 'date',
    options: ['max'],
  },
  {
    section_id: 2,
    section: 'OR',
    question_id: 'age_months',
    question: 'Age (Months)',
    answer_type: 'numeric',
  },
  {
    section_id: 2,
    question_id: 'gender',
    question: 'Gender',
    answer_type: 'radiobox',
    options: [
      {name: 'Male', value: 'Male'},
      {name: 'Female', value: 'Female'}
    ],
    required: true,
  },
  {
    section_id: 2,
    question_id: 'guardian_name',
    question: 'Name of Guardian (If patient is a child)',
    answer_type: 'text',
  },
  {
    section_id: 2,
    question_id: 'patient_address',
    question: 'Address',
    answer_type: 'text',
  },
  {
    section_id: 2,
    question_id: 'patient_phone',
    question: 'Phone Number (self or nearest contact)',
    answer_type: 'phone-pad',
  },
  {
    section_id: 2,
    question_id: 'patient_county',
    question: 'County',
    answer_type: 'dropdown',
    options: 'counties',
  },
  {
    section_id: 2,
    question_id: 'patient_sub_county',
    question_linked: 'patient_county',
    question: 'Sub County',
    answer_type: 'dropdown',
    options: 'subcounties',
  },
  {
    section_id: 2,
    question_id: 'patient_ward',
    question: 'Ward',
    answer_type: 'text',
  },
  {
    section_id: 2,
    question_id: 'patient_village',
    question: 'Village',
    answer_type: 'text',
  },
  {
    section_id: 3,
    question_id: 'vaccination_center',
    question: 'Vaccination Centre',
    answer_type: 'text',
  },
  {
    section_id: 3,
    question_id: 'vaccination_county',
    question: 'County of Vaccination Centre',
    answer_type: 'dropdown',
    options: 'counties',
  },
  {
    section_id: 3,
    question_id: 'vaccination_type',
    question: 'Type of Vaccination Service',
    answer_type: 'dropdown',
    options: [
      {label: 'Select Vaccine Type', value: ''},
      {label: 'Static', value: 'static'},
      {label: 'Mass', value: 'mass'},
      {label: 'Outreach', value: 'outreach'},
    ],
    required: true,
  },
  {
    section_id: 3,
    section: 'Type of AEFI (Select at least one)',
    question_id: 'bcg',
    question: 'BCG Lymphadenitis',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    question_id: 'convulsion',
    question: 'Convulsion',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    question_id: 'urticaria',
    question: 'Generalized urticaria (hives)',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    question_id: 'high_fever',
    question: 'High Fever',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    question_id: 'abscess',
    question: 'Injection site abscess',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    question_id: 'local_reaction',
    question: 'Severe Local Reaction',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    question_id: 'anaphylaxis',
    question: 'Anaphylaxis',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    question_id: 'meningitis',
    question: 'Encephalopathy,Encephalitis/Meningitis',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    question_id: 'paralysis',
    question: 'Paralysis',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    question_id: 'toxic_shock',
    question: 'Toxic Shock',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    question_id: 'complaint_other',
    question: 'Other (type answer)',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    question_id: 'complaint_other_specify',
    question_linked: 'complaint_other',
    question: '',
    answer_type: 'text',
  },
  {
    section_id: 4,
    question_id: 'aefi_symptoms',
    question: 'Describe AEFI',
    answer_type: 'text',
    required: true,
  },
  {
    section_id: 4,
    question_id: 'AefiDescription',
    question: 'AEFI Signs & Symptoms',
    answer_type: 'multitext',
    options: [{question_id: 'description'}],
  },
  {
    section_id: 4,
    question_id: 'description_of_reaction',
    question: 'Brief details on the event (including timeline of occurrence)',
    answer_type: 'text',
    required: true,
  },
  {
    section_id: 4,
    section: 'Onset of event',
    question_id: 'date_aefi_started',
    question: 'Date of onset',
    answer_type: 'date',
    options: ['max'],
    required: true,
  },
  {
    section_id: 4,
    question_id: 'time_aefi_started',
    question: 'Time',
    answer_type: 'time',
  },
  {
    section_id: 5,
    section: 'Suspected vaccine(s)',
    question_id: 'AefiListOfVaccine',
    question_linked: 'date_aefi_started',
    question: '',
    answer_type: 'table',
    required: true,
    headers: 2,
    options: [
      {1: 'Name of Vaccine', 2: ''},
      {1: 'Dose No.', 2: ''},
      {1: 'Date Vaccinated', 2: ''},
      {1: 'Time Vaccinated', 2: ''},
      {1: 'Route of vaccination', 2: ''},
      {1: 'Site of vaccination', 2: ''},
      {1: 'Details of Vaccine', 2: 'Lot/Batch No.'},
      {1: '', 2: 'Manufacturer’s Name'},
      {1: '', 2: 'Expiry Date'},
      {1: 'Details of Diluents', 2: 'Lot/Batch No.'},
      {1: '', 2: 'Manufacturer’s Name'},
      {1: '', 2: 'Expiry Date'},
      {1: 'Action', 2: ''},
    ],
    table_form: [
      {
        order_id: 1,
        question_id: 'vaccine_name',
        question: 'Name of Vaccine(e.g. BCG,DPT-Hib-HeB)',
        answer_type: 'text',
        required: true,
        search: 'vaccines',
        search_url: 'vaccines',
      },
      {
        order_id: 2,
        question_id: 'dosage',
        question: 'Dose No.',
        answer_type: 'text',
      },
      {
        order_id: 3,
        question_id: 'vaccination_date',
        question: 'Date Vaccinated',
        answer_type: 'date',
        options: ['max'],
        required: true,
      },
      {
        order_id: 4,
        question_id: 'vaccination_time',
        question: 'Time Vaccinated',
        answer_type: 'time',
        required: true,
      },
      {
        order_id: 5,
        question_id: 'vaccination_route',
        question: 'Route of vaccination (i.m.,s.c.)',
        answer_type: 'dropdown',
        options: [
          {label: 'Intramascular', value: 'Intramascular'},
          {label: 'Subcutaneous', value: 'Subcutaneous'},
          {label: 'Intradermal', value: 'Intradermal'},
        ],
      },
      {
        order_id: 6,
        question_id: 'vaccination_site',
        question: 'Site of vaccination',
        answer_type: 'text',
      },
      {
        order_id: 7,
        section: 'Details of Vaccine',
        question_id: 'batch_number',
        question: 'Lot/Batch No.',
        answer_type: 'text',
      },
      {
        order_id: 8,
        question_id: 'vaccine_manufacturer',
        question: 'Manufacturer’s Name',
        answer_type: 'text',
      },
      {
        order_id: 9,
        question_id: 'expiry_date',
        question: 'Expiry Date',
        answer_type: 'date',
      },
      {
        order_id: 10,
        section: 'Details of Diluents',
        question_id: 'diluent_batch_number',
        question: 'Lot/Batch No.',
        answer_type: 'text',
      },
      {
        order_id: 11,
        question_id: 'diluent_manufacturer',
        question: 'Manufacturer’s Name',
        answer_type: 'text',
      },
      {
        order_id: 12,
        question_id: 'diluent_expiry_date',
        question: 'Expiry Date',
        answer_type: 'date',
      },
    ],
  },
  {
    section_id: 6,
    question_id: 'medical_history',
    section: 'Past medical history',
    question:
      '(including history of similar reaction or other allergies, concomitant medication/vaccine,concomitant illness, other cases,pregnacy status and other relevant information(continue on separate sheet if necessary)',
    answer_type: 'text',
  },
  {
    section_id: 7,
    section: 'Serious',
    question_id: 'serious',
    question: 'AEFI Serious',
    answer_type: 'radiobox',
    options: [
      {name: 'Yes', value: 'Yes'},
      {name: 'No', value: 'No'},
    ],
    required: true,
  },
  {
    section_id: 7,
    section: 'If Yes',
    question_id: 'serious_yes',
    question_linked: 'serious',
    question: 'Select AEFI seriousness',
    answer_type: 'dropdown',
    options: [
      {label: 'Select Seriousness', value: ''},
      {label: 'Death', value: 'Death'},
      {label: 'Life threatening', value: 'Life threatening'},
      {
        label: 'Persistent or significant disability',
        value: 'Persistent or significant disability',
      },
      {
        label: 'Hospitalization or prolongation of existing hospitalization',
        value: 'Hospitalization or prolongation of existing hospitalization',
      },
      {label: 'Congenital anomaly', value: 'Congenital anomaly'},
      {
        label: 'Other important medical event',
        value: 'Other important medical event',
      },
    ],
  },
  {
    section_id: 7,
    question_id: 'serious_other',
    question: 'Other important medical event',
    answer_type: 'text',
  },
  {
    section_id: 8,
    section: 'Action Taken',
    question_id: 'treatment_given',
    question: 'Treatment given',
    answer_type: 'text',
  },
  {
    section_id: 8,
    question_id: 'specimen_collected',
    question:
      'Specimen collected for investigation (specify type(s) of specimen)',
    answer_type: 'text',
  },
  {
    section_id: 8,
    section: 'AEFI Outcome',
    question_id: 'outcome',
    question: 'Select AEFI Outcome',
    answer_type: 'radiobox',
    options: [
      {name: 'Recovered/Resolved', value: 'Recovered/Resolved'},
      {name: 'Recovering/Resolving', value: 'Recovering/Resolving'},
      {
        name: 'Not recovered/Not resolved/Ongoing',
        value: 'Not recovered/Not resolved/Ongoing',
      },
      {
        name: 'Recovered/Resolved with sequelae',
        value: 'Recovered/Resolved with sequelae',
      },
      {name: 'Unknown', value: 'Unknown'},
      {name: 'Fatal', value: 'Fatal'},
    ],
    required: true,
  },
  {
    section_id: 9,
    question_id: 'Attachment',
    question:
      'Do you have pictures or documents that you would like to send to PPB? click on the button to add them',
    answer_type: 'multiple_image',
    options: [
      {question_id: 'file'},
      {question_id: 'filename'},
      {question_id: 'description'},
    ],
  },
  {
    section_id: 9,
    section: 'Reporter Details',
    question_id: 'reporter_name',
    question: 'Name of Person Reporting',
    answer_type: 'text',
    required: true,
  },
  {
    section_id: 9,
    question_id: 'reporter_email',
    question: 'Email',
    answer_type: 'email-address',
    required: true,
  },
  {
    section_id: 9,
    question_id: 'designation_id',
    question: 'Designation',
    answer_type: 'dropdown',
    options: 'designations',
    required: true,
  },
  {
    section_id: 9,
    question_id: 'reporter_phone',
    question: 'Phone Number',
    answer_type: 'phone-pad',
    required: true,
  },
  {
    section_id: 9,
    question_id: 'reporter_date',
    question: 'Reporting date',
    answer_type: 'date',
    required: true,
  },

  {
    section_id: 9,
    section: 'Is the person submitting different from reporter?',
    question_id: 'person_submitting',
    question: 'Reporter different?',
    answer_type: 'radiobox',
    options: [
      {name: 'Yes', value: 'Yes'},
      {name: 'No', value: 'No'},
    ],
    required: true,
  },
  {
    section_id: 9,
    question_id: 'reporter_name_diff',
    question: 'Name',
    answer_type: 'text',
  },
  {
    section_id: 9,
    question_id: 'reporter_email_diff',
    question: 'Email Address',
    answer_type: 'email-address',
  },
  {
    section_id: 9,
    question_id: 'reporter_designation_diff',
    question: 'Designation',
    answer_type: 'dropdown',
    options: 'designations',
  },
  {
    section_id: 9,
    question_id: 'reporter_phone_diff',
    question: 'Phone Number',
    answer_type: 'phone-pad',
  },
  {
    section_id: 9,
    question_id: 'reporter_date_diff',
    question: 'Date',
    answer_type: 'date',
  },
];
