export const device = [
  {
    section_id: 1,
    question_id: 'report_title',
    question: 'Report Title',
    answer_type: 'text',
    search: 'dynamic',
    search_url: 'meddras',
    required: true,
  },
  {
    section_id: 1,
    question_id: 'name_of_institution',
    question: 'Name of institution/Organization',
    answer_type: 'text',
    search: 'institute',
    search_url: 'facility_codes',
    required: true,
  },
  {
    section_id: 1,
    question_id: 'institution_code',
    question: 'Institution Code',
    answer_type: 'text',
    search: 'institute',
    search_url: 'facility_codes',
  },
  {
    section_id: 1,
    question_id: 'institution_address',
    question: 'Institution Address',
    answer_type: 'text',
    required: true,
  },
  {
    section_id: 1,
    question_id: 'institution_contact',
    question: ' Institution Contact',
    answer_type: 'text',
  },
  {
    section_id: 1,
    question_id: 'county_id',
    question: 'County',
    answer_type: 'dropdown',
    options: 'counties',
    required: true,
  },
  {
    section_id: 2,
    section: 'Patient Information',
    question_id: 'patient_name',
    question: "Patient's Initials",
    answer_type: 'text',
    required: true,
  },
  {
    section_id: 2,
    question_id: 'ip_no',
    question: 'IP/OP NO',
    answer_type: 'text',
  },
  {
    section_id: 2,
    question_id: 'date_of_birth',
    question: 'Date of Birth',
    answer_type: 'date',
    options: ['max'],
  },
  {
    section_id: 2,
    section: 'OR',
    question_id: 'age_years',
    question: 'Age Group',
    answer_type: 'dropdown',
    options: [
      {label: 'Select Age Group', value: ''},
      {label: 'neonate ( 0 - 1 month)', value: 'neonate'},
      {label: 'infant (1 month -1 year)', value: 'infant'},
      {label: 'child (1 - 11 years)', value: 'child'},
      {label: 'adolescent ( 12-17 years)', value: 'adolescent'},
      {label: 'adult (18-64 years)', value: 'adult'},
      {label: 'elderly (>65 years)', value: 'elderly'},
    ],
  },
  {
    section_id: 2,
    question_id: 'gender',
    question: 'Gender',
    answer_type: 'radiobox',
    options: [
      {name: 'Male', value: 'Male'},
      {name: 'Female', value: 'Female'},
      {name: 'Unknown', value: 'Unknown'},
    ],
    required: true,
  },
  {
    section_id: 2,
    question_id: 'pregnancy_status',
    question_linked: 'gender',
    answer_expect: 'Male',
    question: 'Pregnancy Status',
    answer_type: 'radiobox',
    options: [
      {name: 'Not Applicable', value: 'Not Applicable'},
      {name: 'Not pregnant', value: 'Not pregnant'},
      {name: '1st Trimester', value: '1st Trimester'},
      {name: '2nd Trimester', value: '2nd Trimester'},
      {name: '3rd Trimester', value: '3rd Trimester'},
    ],
  },
  {
    section_id: 2,
    question_id: 'patient_address',
    question: 'Patient Address',
    answer_type: 'text',
  },
  {
    section_id: 2,
    question_id: 'patient_phone',
    question: 'Phone Number (self or nearest contact) ',
    answer_type: 'phone-pad',
  },
  {
    section_id: 2,
    question_id: 'allergy',
    question: 'Any Known Allergies?',
    answer_type: 'radiobox',
    options: [
      {name: 'Yes', value: 'Yes'},
      {name: 'No', value: 'No'},
    ],
    required: true,
  },
  {
    section_id: 2,
    question_id: 'allergy_specify',
    question_linked: 'allergy',
    question: 'Allergy',
    answer_type: 'text',
  },
  {
    section_id: 2,
    question_id: 'patient_weight',
    question: 'Weight (Kg)',
    answer_type: 'numeric',
  },
  {
    section_id: 2,
    question_id: 'patient_height',
    question: 'Height (cm)',
    answer_type: 'numeric',
  },
  {
    section_id: 3,
    section: 'Device/In vitro Diagnostic information',
    question_id: 'problem_noted',
    question: 'Problem noted prior to use',
    answer_type: 'radiobox',
    options: [
      {name: 'Yes', value: 'Yes'},
      {name: 'No', value: 'No'},
    ],
    required: true,
  },
  {
    section_id: 3,
    question_id: 'brand_name',
    question: 'Brand Name/ Commercial Name ',
    answer_type: 'text',
    required: true,
  },
  {
    section_id: 3,
    question_id: 'device_model',
    question: 'Model',
    answer_type: 'text',
  },
  {
    section_id: 3,
    question_id: 'serial_no',
    question: 'Serial/ Lot No.',
    answer_type: 'text',
    required: true,
  },
  {
    section_id: 3,
    question_id: 'catalogue',
    question: 'Catalogue Number',
    answer_type: 'text',
  },
  {
    section_id: 3,
    question_id: 'manufacturer_name',
    question: 'Name of manufacturer',
    answer_type: 'text',
    required: true,
  },
  {
    section_id: 3,
    question_id: 'manufacturer_address',
    question: 'Manufacturer Address',
    answer_type: 'text',
  },
  {
    section_id: 3,
    question_id: 'manufacture_date',
    question: 'Devcie Manufacture date',
    answer_type: 'date',
    options: ['max'],
    required: true,
  },
  {
    section_id: 3,
    question_id: 'expiry_date',
    question: 'Expiry date',
    answer_type: 'date',
    required: true,
  },
  {
    section_id: 4,
    question_id: 'operator',
    question: 'Operator of the device at time of onset',
    answer_type: 'radiobox',
    options: [
      {name: 'Healthcare professional', value: 'Healthcare professional'},
      {name: 'Patient', value: 'Patient'},
      {name: 'Caregiver', value: 'Caregiver'},
      {name: 'Other', value: 'Other'},
    ],
  },
  {
    section_id: 4,
    section_linked: 'Other',
    question_id: 'operator_specify',
    question_linked: 'operator',
    question: 'Other(specify)',
    answer_type: 'text',
  },
  {
    section_id: 4,
    question_id: 'device_usage',
    question: 'Usage of device (choose whichever applies)',
    answer_type: 'radiobox',
    options: [
      {name: 'Single use', value: 'Single use'},
      {name: 'Reuse of reusable', value: 'Reuse of reusable'},
      {name: 'Reuse of single-use', value: 'Reuse of single-use'},
      {name: 'Reserviced/Refurbished', value: 'Reserviced/Refurbished'},
    ],
  },
  {
    section_id: 5,
    question_id: 'device_duration_type',
    question: 'How long was the device/ equipment/ machine in use',
    answer_type: 'dropdown',
    options: [
      {label: 'Select Duration', value: ''},
      {label: 'Days', value: 'Days'},
      {label: 'Months', value: 'Months'},
      {label: 'Years', value: 'Years'},
    ],
  },
  {
    section_id: 5,
    question_id: 'device_duration',
    question: 'Duration',
    answer_type: 'numeric',
  },
  {
    section_id: 5,
    question_id: 'device_availability',
    question: 'Availability of device for evaluation',
    answer_type: 'radiobox',
    options: [
      {name: 'Yes', value: 'Yes'},
      {name: 'No', value: 'No'},
    ],
    required: true,
  },
  {
    section_id: 5,
    question_id: 'device_unavailability',
    question_linked: 'device_availability',
    question: 'If No',
    answer_type: 'radiobox',
    options: [
      {name: 'Device destroyed', value: 'Device destroyed'},
      {name: 'Still in use', value: 'Still in use'},
      {
        name: 'Returned to manufacturer/importer/distributor',
        value: 'Returned to manufacturer/importer/distributor',
      },
    ],
  },
  {
    section_id: 6,
    section: 'For implants only (e.g. intrauterine devices, pacemakers)',
    question_id: 'implant_date',
    question: 'Implant date',
    answer_type: 'date',
  },
  {
    section_id: 6,
    question_id: 'explant_date',
    question_linked: 'implant_date',
    question: 'Explant date',
    answer_type: 'date',
  },
  {
    section_id: 6,
    question_id: 'implant_duration_type',
    question:
      'Duration of implantation (to be filled if the exact implant and explant dates are unknown) ',
    answer_type: 'dropdown',
    options: [
      {label: 'Select Duration', value: ''},
      {label: 'Days', value: 'Days'},
      {label: 'Months', value: 'Months'},
      {label: 'Years', value: 'Years'},
    ],
  },
  {
    section_id: 6,
    question_id: 'implant_duration',
    question: 'Duration',
    answer_type: 'numeric',
  },
  {
    section_id: 7,
    section:
      'For diagnostics only (including machines and equipment e.g. rapid diagnostic test kits, glucometer)',
    question_id: 'specimen_type',
    question: 'Type of specimen used(e.g. blood, saliva, etc)',
    answer_type: 'text',
  },
  {
    section_id: 7,
    question_id: 'patients_involved',
    question: 'No. of patients involved',
    answer_type: 'numeric',
  },
  {
    section_id: 7,
    question_id: 'tests_done',
    question: 'No. of tests done',
    answer_type: 'numeric',
  },
  {
    section_id: 7,
    question_id: 'false_positives',
    question: 'No. of false positives',
    answer_type: 'numeric',
  },
  {
    section_id: 7,
    question_id: 'false_negatives',
    question: 'No. of false negatives',
    answer_type: 'numeric',
  },
  {
    section_id: 7,
    question_id: 'true_positives',
    question: 'No. of true positives',
    answer_type: 'numeric',
  },
  {
    section_id: 7,
    question_id: 'true_negatives',
    question: 'No. of true negatives',
    answer_type: 'numeric',
  },
  {
    section_id: 8,
    section: 'List of other/associated devices involved in the event',
    question_id: 'ListOfDevice',
    question: '',
    answer_type: 'table',
    headers: 1,
    options: [
      {1: 'Brand/Commercial Name'},
      {1: 'Serial/Lot No.'},
      {1: 'Common Name'},
      {1: 'Manufacturer'},
      {1: 'Manufacturer Date'},
      {1: 'Expiry date'},
      {1: 'Action'},
    ],
    table_form: [
      {
        order_id: 1,
        question_id: 'brand_name',
        question: 'Brand/Commercial Name',
        answer_type: 'text',
      },
      {
        order_id: 2,
        question_id: 'serial_no',
        question: 'Serial/Lot No.',
        answer_type: 'text',
      },
      {
        order_id: 3,
        question_id: 'common_name',
        question: 'Common Name.',
        answer_type: 'text',
      },
      {
        order_id: 4,
        question_id: 'manufacturer',
        question: 'Manufacturer Name',
        answer_type: 'text',
        required: true,
      },
      {
        order_id: 5,
        question_id: 'manufacture_date',
        question: 'Manufacturer Date',
        answer_type: 'date',
        options: ['max'],
      },
      {
        order_id: 6,
        question_id: 'expiry_date',
        question: 'Expiry Date',
        answer_type: 'date',
      },
    ],
  },
  {
    section_id: 9,
    section: 'Incident Information',
    question_id: 'date_onset_incident',
    question: 'Date of onset of the incident',
    answer_type: 'date',
    options: ['max'],
    required: true,
  },
  {
    section_id: 9,
    question_id: 'serious',
    question: 'Event classification',
    answer_type: 'radiobox',
    options: [
      {name: 'Mild', value: 'Mild'},
      {name: 'Moderate', value: 'Moderate'},
      {name: 'Serious', value: 'Serious'},
      {name: 'Fatal', value: 'Fatal'},
      {name: 'Unknown', value: 'Unknown'},
    ],
    required: true,
  },
  {
    section_id: 9,
    question_id: 'serious_yes',
    question_linked: 'serious',
    question: 'Criteria/reason for seriousness',
    answer_type: 'radiobox',
    options: [
      {
        name: 'Hospitalization or prolongation of existing hospitalization',
        value: 'Hospitalization or prolongation of existing hospitalization',
      },
      {
        name: 'Results in persistent or significant disability',
        value: 'Results in persistent or significant disability',
      },
      {
        name: 'Congenital anomality or birth defect',
        value: 'Congenital anomality or birth defect',
      },
      {name: 'Life-threatening', value: 'Life-threatening'},
      {name: 'Death ', value: 'Death '},
    ],
  },
  {
    section_id: 9,
    question_id: 'death_date',
    question_linked: 'serious_yes',
    question: 'Date of Death',
    answer_type: 'date',
    options: ['max'],
  },
  {
    section_id: 10,
    question_id: 'description_of_reaction',
    question: 'Description of event',
    answer_type: 'text',
  },
  {
    section_id: 10,
    question_id: 'remedial_action',
    question:
      'Remedial Action/Corrective action/preventive action taken by the healthcare facility relevant to the care of the patient',
    answer_type: 'text',
  },
  {
    section_id: 10,
    question_id: 'outcome',
    question: 'Patient Outcome',
    answer_type: 'radiobox',
    options: [
      {name: 'Recovered', value: 'Recovered'},
      {name: 'Recovering', value: 'Recovering'},
      {name: 'Not recovered', value: 'Not recovered'},
      {name: 'Recovered with sequelae', value: 'Recovered with sequelae'},
      {name: 'Unknown', value: 'Unknown'},
      {name: 'Fatal', value: 'Fatal'},
    ],
    required: true,
  },
  {
    section_id: 11,
    question_id: 'Attachment',
    question:
      'Do you have pictures or documents that you would like to send to PPB? click on the button to add them',
    answer_type: 'multiple_image',
    options: [
      {question_id: 'file'},
      {question_id: 'filename'},
      {question_id: 'description'},
    ],
  },
  {
    section_id: 11,
    section: 'Reporter Details',
    question_id: 'reporter_name',
    question: 'Name of Person Reporting',
    answer_type: 'text',
    required: true,
  },
  {
    section_id: 11,
    question_id: 'reporter_email',
    question: 'Email',
    answer_type: 'email-address',
    required: true,
  },
  {
    section_id: 11,
    question_id: 'designation_id',
    question: 'Designation',
    answer_type: 'dropdown',
    options: 'designations',
    required: true,
  },
  {
    section_id: 11,
    question_id: 'reporter_phone',
    question: 'Phone Number',
    answer_type: 'phone-pad',
    required: true,
  },
  {
    section_id: 11,
    question_id: 'reporter_date',
    question: 'Reporting date',
    answer_type: 'date',
    required: true,
  },

  {
    section_id: 11,
    section: 'Is the person submitting different from reporter?',
    question_id: 'person_submitting',
    question: 'Reporter different?',
    answer_type: 'radiobox',
    options: [
      {name: 'Yes', value: 'Yes'},
      {name: 'No', value: 'No'},
    ],
    required: true,
  },
  {
    section_id: 11,
    question_id: 'reporter_name_diff',
    question: 'Name',
    answer_type: 'text',
  },
  {
    section_id: 11,
    question_id: 'reporter_email_diff',
    question: 'Email Address',
    answer_type: 'email-address',
  },
  {
    section_id: 11,
    question_id: 'reporter_designation_diff',
    question: 'Designation',
    answer_type: 'dropdown',
    options: 'designations',
  },
  {
    section_id: 11,
    question_id: 'reporter_phone_diff',
    question: 'Phone Number',
    answer_type: 'phone-pad',
  },
  {
    section_id: 11,
    question_id: 'reporter_date_diff',
    question: 'Date',
    answer_type: 'date',
  },
];
