export const padr = [
  {
    section_id: 1,
    section: 'Details of the Person Reporting',
    question_id: 'reporter_name',
    question: 'Name of Person Reporting ',
    answer_type: 'text',
    required: true,
  },
  {
    section_id: 1,
    question_id: 'reporter_email',
    question: 'Email Address',
    answer_type: 'email-address',
    required: true,
  },
  {
    section_id: 1,
    question_id: 'reporter_phone',
    question: 'Mobile No.',
    answer_type: 'phone-pad',
    required: true,
    note:'Your phone number is important for follow up by the Pharmacy and Poisons Board and to obtain additional information as well as providing you with the feedback'
  },
  {
    section_id: 1,
    question_id: 'county_id',
    question: 'County',
    answer_type: 'dropdown',
    options: 'counties',
    required: true,
  },
  {
    section_id: 1,
    question_id: 'relation',
    question: 'Relation',
    answer_type: 'dropdown',
    options: [
      {label: 'Select Relation', value: ''},
      {label: 'Self', value: 'Self'},
      {label: 'Parent', value: 'Parent'},
      {label: 'Guardian', value: 'Guardian'},
      {label: 'Other', value: 'Other'},
    ],
  },
  {
    section_id: 2,
    section: 'Details of the Patient',
    question_id: 'patient_name',
    question: "Patient's Name ",
    answer_type: 'text',
    required: true,
  },
  {
    section_id: 2,
    question_id: 'gender',
    question: 'Gender',
    answer_type: 'radiobox',
    options: [
      {name: 'Male', value: 'Male'},
      {name: 'Female', value: 'Female'},
    ],
  },
  {
    section_id: 2,
    question_id: 'date_of_birth',
    question: 'Date of Birth',
    answer_type: 'date',
    options: ['max'],
  },
  {
    section_id: 2,
    section: 'OR',
    question_id: 'age_group',
    question: 'Age Group',
    answer_type: 'dropdown',
    options: [
      {label: 'Select Age Group', value: ''},
      {label: 'neonate ( 0 - 1 month)', value: 'neonate'},
      {label: 'infant (1 month -1 year)', value: 'infant'},
      {label: 'child (1 - 11 years)', value: 'child'},
      {label: 'adolescent ( 12-17 years)', value: 'adolescent'},
      {label: 'adult (18-64 years)', value: 'adult'},
      {label: 'elderly (>65 years)', value: 'elderly'},
    ],
  },
  {
    section_id: 3,
    question_id: 'report_sadr',
    question: 'Select type of report',
    answer_type: 'radiobox',
    options: [
      {name: 'Adverse Reaction', value: 'Adverse Reaction'},
      {name: 'Poor Quality Medicine', value: 'Poor Quality Medicine'},
    ],
    required: true,
  },
  {
    section_id: 3,
    section_linked: 'Adverse Reaction',
    section: 'Side Effect (Select all side effects experienced)',
    question_id: 'sadr_vomiting',
    question_linked: 'report_sadr',
    question: 'Vomiting or diarrhoea',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    section_linked: 'Adverse Reaction',
    question_id: 'sadr_dizziness',
    question_linked: 'report_sadr',
    question: 'Dizziness or drowsiness  ',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    section_linked: 'Adverse Reaction',
    question_id: 'sadr_headache',
    question_linked: 'report_sadr',
    question: 'Headache',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    section_linked: 'Adverse Reaction',
    question_id: 'sadr_joints',
    question_linked: 'report_sadr',
    question: 'Joints and muscle pain',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    section_linked: 'Adverse Reaction',
    question_id: 'sadr_rash',
    question_linked: 'report_sadr',
    question: 'Rash, itching, swelling on skin',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    section_linked: 'Adverse Reaction',
    question_id: 'sadr_mouth',
    question_linked: 'report_sadr',
    question: 'Pain or bleeding in the mouth',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    section_linked: 'Adverse Reaction',
    question_id: 'sadr_stomach',
    question_linked: 'report_sadr',
    question: 'Pain in the stomach',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    section_linked: 'Adverse Reaction',
    question_id: 'sadr_urination',
    question_linked: 'report_sadr',
    question: 'Abnormal changes with urination',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    section_linked: 'Adverse Reaction',
    question_id: 'sadr_eyes',
    question_linked: 'report_sadr',
    question: 'Red, painful eyes',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    section_linked: 'Adverse Reaction',
    question_id: 'sadr_died',
    question_linked: 'report_sadr',
    question: 'Patient died ',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    section_linked: 'Adverse Reaction',
    question_id: 'description_of_reaction',
    question_linked: 'report_sadr',
    question:
      'Other side effects experienced. What were the signs of the side effect?',
    answer_type: 'text',
  },
  {
    section_id: 3,
    section_linked: 'Adverse Reaction',
    question_id: 'date_of_onset_of_reaction',
    question_linked: 'report_sadr',
    question: 'When did the reaction start? ',
    answer_type: 'date',
    options: ['max'],
  },
  {
    section_id: 3,
    section_linked: 'Adverse Reaction',
    question_id: 'reaction_on',
    question_linked: 'report_sadr',
    question: 'Is the reaction still on?',
    answer_type: 'radiobox',
    options: [
      {name: 'Yes', value: 'Yes'},
      {name: 'No', value: 'No'},
    ],
  },

  {
    section_id: 3,
    section_linked: 'Poor Quality Medicine',
    section:
      'Poor Quality Medicine (Select all issues with the medicine/device)',
    question_id: 'pqmp_label',
    question_linked: 'report_sadr',
    question: 'The label looks wrong ',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    section_linked: 'Poor Quality Medicine',
    question_id: 'pqmp_material',
    question_linked: 'report_sadr',
    question: 'Has unusual material in it ',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    section_linked: 'Poor Quality Medicine',
    question_id: 'pqmp_color',
    question_linked: 'report_sadr',
    question: 'The color is changing ',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    section_linked: 'Poor Quality Medicine',
    question_id: 'pqmp_smell',
    question_linked: 'report_sadr',
    question: 'The smell is unusual',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    section_linked: 'Poor Quality Medicine',
    question_id: 'pqmp_working',
    question_linked: 'report_sadr',
    question: 'The medicine/device is not working ',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    section_linked: 'Poor Quality Medicine',
    question_id: 'pqmp_bottle',
    question_linked: 'report_sadr',
    question: 'The packet or bottle does not seem to be usual or complete ',
    answer_type: 'checkbox',
  },
  {
    section_id: 3,
    section_linked: 'Poor Quality Medicine',
    question_id: 'any_other_comment',
    question_linked: 'report_sadr',
    question: 'Other wrong things . Additional wrong things?',
    answer_type: 'text',
  },
  {
    section_id: 4,
    section:
      'DETAILS OF THE MEDICINE/VACCINE/DEVICE THAT CAUSED THE REACTION (Include all medications)',
    question_id: 'PadrListOfMedicine',
    question: '',
    answer_type: 'table',
    required: true,
    headers: 1,
    options: [
      {1: 'Name of Medicine/Vaccine/Device '},
      {1: 'Manufacturer'},
      {1: 'Start Date'},
      {1: 'Stop Date'},
      {1: 'Expiry date'},
      {1: 'Where did you buy the medicine/vaccine/device? '},
      {1: 'Action'},
    ],
    table_form: [
      {
        order_id: 1,
        question_id: 'product_name',
        question: 'Name of Medicine/Vaccine/Device ',
        answer_type: 'text',
        required: true,
      },
      {
        order_id: 2,
        question_id: 'manufacturer',
        question: 'Manufacturer',
        answer_type: 'text',
      },
      {
        order_id: 3,
        question_id: 'start_date',
        question:
          'When did you start taking/using the medicine/vaccine/device?',
        answer_type: 'date',
        options: ['max'],
      },
      {
        order_id: 4,
        question_id: 'end_date',
        question_linked: 'start_date',
        question:
          'When did you stop taking/using the medicine/vaccine/device? ',
        answer_type: 'date',
      },
      {
        order_id: 5,
        question_id: 'expiry_date',
        question: 'Expiry date of the medicine/vaccine/device',
        answer_type: 'date',
      },
      {
        order_id: 6,
        question_id: 'medicine_source',
        question: 'Where did you buy the medicine/vaccine/device? ',
        answer_type: 'text',
      },
    ],
  },
  {
    section_id: 5,
    question_id: 'outcome',
    question: 'Outcome',
    answer_type: 'radiobox',
    options: [
      {name: 'Recovered/resolved', value: 'Recovered/resolved'},
      {name: 'Recovering/resolving', value: 'Recovering/resolving'},
      {
        name: 'Recovered/resolved with sequelae',
        value: 'Recovered/resolved with sequelae',
      },
      {name: 'Not recovered/not resolved', value: 'Not recovered/not resolved'},
      {name: 'Death', value: 'Death'},
      {name: 'Unknown', value: 'Unknown'},
    ],
    required: true,
  },
  {
    section_id: 6,
    question_id: 'Attachment',
    question:
      'Do you have pictures or documents that you would like to send to PPB? click on the button to add them',
    answer_type: 'multiple_image',
    options: [
      {question_id: 'file'},
      {question_id: 'filename'},
      {question_id: 'description'},
    ],
  },
  {
    section_id: 6, 
    question_id: 'consent',
    section:'If we need further information to help us understand the case do we have your permission to contact you?',
    question: 'Consent',
    answer_type: 'dropdown',
    required: true,
    options: [
      {label: 'Yes', value: 'Yes'},
      {label: 'No', value: 'No'},
    ],
  },
];
