export const pqmp = [
  {
    section_id: 1,
    section: 'Product category (Tick appropriate box)',
    question_id: 'medicinal_product',
    question: 'Medicinal product ',
    answer_type: 'checkbox',
  },
  {
    section_id: 1,
    question_id: 'blood_products',
    question: 'Blood and blood products ',
    answer_type: 'checkbox',
  },
  {
    section_id: 1,
    question_id: 'herbal_product',
    question: 'Herbal product ',
    answer_type: 'checkbox',
  },
  {
    section_id: 1,
    question_id: 'medical_device',
    question: 'Medical device',
    answer_type: 'checkbox',
  },
  {
    section_id: 1,
    question_id: 'product_vaccine',
    question: 'Vaccine ',
    answer_type: 'checkbox',
  },
  {
    section_id: 1,
    question_id: 'cosmeceuticals',
    question: 'Cosmeceuticals ',
    answer_type: 'checkbox',
  },
  {
    section_id: 1,
    question_id: 'product_other',
    question: 'Other (type answer)',
    answer_type: 'checkbox',
  },
  {
    section_id: 1,
    question_id: 'product_specify',
    question_linked: 'product_other',
    question: '',
    answer_type: 'text',
  },
  {
    section_id: 2,
    section: 'Facility Details',
    question_id: 'facility_name',
    question: 'Name of Facility',
    answer_type: 'text',
    search: 'facility',
    search_url: 'facility_codes',
  },
  {
    section_id: 2,
    question_id: 'facility_code',
    question: 'Facility Code',
    answer_type: 'text',
    search: 'facility',
    search_url: 'facility_codes',
  },
  {
    section_id: 2,
    question_id: 'facility_address',
    question: 'Facility Address',
    answer_type: 'text',
  },
  {
    section_id: 2,
    question_id: 'facility_phone',
    question: 'Facility Phone',
    answer_type: 'phone-pad',
  },
  {
    section_id: 2,
    question_id: 'county_id',
    question: 'County',
    answer_type: 'dropdown',
    options: 'counties',
  },
  {
    section_id: 2,
    question_id: 'sub_county_id',
    question_linked: 'county_id',
    question: 'Sub County',
    answer_type: 'dropdown',
    options: 'subcounties',
  },
  {
    section_id: 3,
    section: 'Product Identity',
    question_id: 'brand_name',
    question: 'Brand Name',
    answer_type: 'text',
    required: true,
  },
  {
    section_id: 3,
    question_id: 'generic_name',
    question: 'Generic Name',
    answer_type: 'text',
  },
  {
    section_id: 3,
    question_id: 'batch_number',
    question: 'Batch/Lot Number',
    answer_type: 'text',
  },
  {
    section_id: 3,
    question_id: 'supplier_name',
    question: 'Name of Distributor / Supplier',
    answer_type: 'text',
  },
  {
    section_id: 3,
    question_id: 'supplier_address',
    question: "Distributor/ Supplier's Address",
    answer_type: 'text',
  },
  {
    section_id: 4,
    question_id: 'name_of_manufacturer',
    question: 'Name of Manufacturer ',
    answer_type: 'text',
    required: true,
  },
  {
    section_id: 4,
    question_id: 'manufacture_date',
    question: 'Date of Manufacture',
    answer_type: 'date',
    options: ['max'],
    required: true,
  },
  {
    section_id: 4,
    question_id: 'expiry_date',
    question: 'Date of Expiry ',
    answer_type: 'date',
    required: true,
  },
  {
    section_id: 4,
    question_id: 'receipt_date',
    question_linked: 'manufacture_date',
    question: 'Date of Receipt',
    answer_type: 'date',
  },
  {
    section_id: 4,
    question_id: 'country_of_origin',
    question: 'Country of Origin',
    answer_type: 'dropdown',
    options: 'countries',
  },
  {
    section_id: 4,
    question_id: 'name_of_distributor',
    question: 'Name of Distributor/Supplier ',
    answer_type: 'text',
    required: false,
  },
  {
    section_id: 4,
    question_id: 'distributor_address',
    question: 'Distributor/Supplier Address',
    answer_type: 'text',
    required: false,
  },
  {
    section_id: 5,
    section: 'Product Formulation',
    question_id: 'product_formulation',
    question: '(Tick appropriate box)',
    answer_type: 'radiobox',
    options: [
      {name: 'Oral tablets / capsules', value: 'Oral tablets / capsules'},
      {name: 'Oral suspension / syrup', value: 'Oral suspension / syrup'},
      {name: 'Injection', value: 'Injection'},
      {name: 'Diluent', value: 'Diluent'},
      {
        name: 'Powder for Reconstitution of Suspension',
        value: 'Powder for Reconstitution of Suspension',
      },
      {
        name: 'Powder for Reconstitution of Injection',
        value: 'Powder for Reconstitution of Injection',
      },
      {name: 'Eye drops', value: 'Eye drops'},
      {name: 'Ear drops', value: 'Ear drops'},
      {name: 'Nebuliser solution', value: 'Nebuliser solution'},
      {
        name: 'Cream / Ointment / Liniment / Paste',
        value: 'Cream / Ointment / Liniment / Paste',
      },
      {
        name: 'Anticoagulant (for blood and blood products)',
        value: 'Anticoagulant (for blood and blood products)',
      },
      {name: 'Other', value: 'Other'},
    ],
    required: true,
  },
  {
    section_id: 5,
    question_id: 'product_formulation_specify',
    question_linked: 'product_formulation',
    question: '',
    answer_type: 'text',
  },
  {
    section_id: 6,
    section: 'Complaint (Tick appropriate box/boxes)',
    question_id: 'colour_change',
    question: 'Colour change ',
    answer_type: 'checkbox',
  },
  {
    section_id: 6,
    question_id: 'separating',
    question: 'Separating',
    answer_type: 'checkbox',
  },
  {
    section_id: 6,
    question_id: 'powdering',
    question: 'Powdering / crumbling',
    answer_type: 'checkbox',
  },
  {
    section_id: 6,
    question_id: 'caking',
    question: 'Caking ',
    answer_type: 'checkbox',
  },
  {
    section_id: 6,
    question_id: 'moulding',
    question: 'Moulding',
    answer_type: 'checkbox',
  },
  {
    section_id: 6,
    question_id: 'odour_change',
    question: 'Change of odour',
    answer_type: 'checkbox',
  },
  {
    section_id: 6,
    question_id: 'mislabeling',
    question: 'Mislabeling',
    answer_type: 'checkbox',
  },
  {
    section_id: 6,
    question_id: 'incomplete_pack',
    question: 'Incomplete pack',
    answer_type: 'checkbox',
  },
  {
    section_id: 6,
    question_id: 'therapeutic_ineffectiveness',
    question: 'Therapeutic ineffectiveness',
    answer_type: 'checkbox',
  },
  {
    section_id: 6,
    question_id: 'particulate_matter',
    question: 'Particulate matter in infusions/injectables ',
    answer_type: 'checkbox',
  },
  {
    section_id: 6,
    question_id: 'complaint_other',
    question: 'Other (type answer)',
    answer_type: 'checkbox',
  },
  {
    section_id: 6,
    question_id: 'complaint_other_specify',
    question_linked: 'complaint_other',
    question: '',
    answer_type: 'text',
  },
  {
    section_id: 7,
    section: 'For medical device and invitro diagnostic',
    section_linked: '1',
    question_id: 'packaging',
    question_linked: 'medical_device',
    question: 'Packaging',
    answer_type: 'checkbox',
  },
  {
    section_id: 7,
    section_linked: '1',
    question_id: 'labelling',
    question_linked: 'medical_device',
    question: 'Labelling',
    answer_type: 'checkbox',
  },
  {
    section_id: 7,
    section_linked: '1',
    question_id: 'sampling',
    question_linked: 'medical_device',
    question: 'Sampling',
    answer_type: 'checkbox',
  },
  {
    section_id: 7,
    section_linked: '1',
    question_id: 'mechanism',
    question_linked: 'medical_device',
    question: 'Mechanism',
    answer_type: 'checkbox',
  },
  {
    section_id: 7,
    section_linked: '1',
    question_id: 'electrical',
    question_linked: 'medical_device',
    question: 'Electrical',
    answer_type: 'checkbox',
  },
  {
    section_id: 7,
    section_linked: '1',
    question_id: 'device_data',
    question_linked: 'medical_device',
    question: 'Data',
    answer_type: 'checkbox',
  },
  {
    section_id: 7,
    section_linked: '1',
    question_id: 'software',
    question_linked: 'medical_device',
    question: 'Software',
    answer_type: 'checkbox',
  },
  {
    section_id: 7,
    section_linked: '1',
    question_id: 'environmental',
    question_linked: 'medical_device',
    question: 'Environmental',
    answer_type: 'checkbox',
  },
  {
    section_id: 7,
    section_linked: '1',
    question_id: 'failure_to_calibrate',
    question_linked: 'medical_device',
    question: 'Failure to calibrate',
    answer_type: 'checkbox',
  },
  {
    section_id: 7,
    section_linked: '1',
    question_id: 'results',
    question_linked: 'medical_device',
    question: 'Results',
    answer_type: 'checkbox',
  },
  {
    section_id: 7,
    section_linked: '1',
    question_id: 'readings',
    question_linked: 'medical_device',
    question: 'Readings',
    answer_type: 'checkbox',
  },
  {
    section_id: 7,
    question_id: 'complaint_description',
    section: 'Describe the complaint in detail ',
    question: 'complaint description',
    answer_type: 'text',
    required: true,
  },
  {
    section_id: 8,
    question_id: 'cold_chain',
    question:
      'Was the cold chain maintained for both transportation and storage?',
    answer_type: 'radiobox',
    options: [
      {name: 'Yes', value: 'Yes'},
      {name: 'No', value: 'No'},
      {name: 'Not Sure', value: 'Not Sure'},
    ],
  },
  {
    section_id: 8,
    question_id: 'require_refrigeration',
    question: 'Does the product require refrigeration?',
    answer_type: 'radiobox',
    options: [
      {name: 'Yes', value: 'Yes'},
      {name: 'No', value: 'No'},
    ],
  },
  {
    section_id: 8,
    question_id: 'product_at_facility',
    question: 'Was the product available at the facility?',
    answer_type: 'radiobox',
    options: [
      {name: 'Yes', value: 'Yes'},
      {name: 'No', value: 'No'},
    ],
  },
  {
    section_id: 8,
    question_id: 'returned_by_client',
    question: 'Was the product dispensed and returned by client?',
    answer_type: 'radiobox',
    options: [
      {name: 'Yes', value: 'Yes'},
      {name: 'No', value: 'No'},
    ],
  },
  {
    section_id: 8,
    question_id: 'stored_to_recommendations',
    question:
      'Was the product stored according to Manufacturer / MOH recommendations?',
    answer_type: 'radiobox',
    options: [
      {name: 'Yes', value: 'Yes'},
      {name: 'No', value: 'No'},
    ],
  },
  {
    section_id: 8,
    question_id: 'result_in_adverse_drug_reaction',
    question: 'Did the drug result in an adverse drug reaction?',
    answer_type: 'radiobox',
    options: [
      {name: 'Yes', value: 'Yes'},
      {name: 'No', value: 'No'},
    ],
  },
  {
    section_id: 8,
    question_id: 'result_in_medical_error',
    question: 'Did the product result in a medication error?',
    answer_type: 'radiobox',
    options: [
      {name: 'Yes', value: 'Yes'},
      {name: 'No', value: 'No'},
    ],
  },
  {
    section_id: 9,
    question_id: 'other_details',
    question: 'Other Details If Necessary',
    answer_type: 'text',
  },
  {
    section_id: 9,
    question_id: 'comments',
    question: 'Comments (if any)',
    answer_type: 'text',
  },
  {
    section_id: 9,
    question_id: 'Attachment',
    question:
      'Do you have pictures or documents that you would like to send to PPB? click on the button to add them',
    answer_type: 'multiple_image',
    options: [
      {question_id: 'file'},
      {question_id: 'filename'},
      {question_id: 'description'},
    ],
  },
  {
    section_id: 10,
    section: 'Reporter Details',
    question_id: 'reporter_name',
    question: 'Name of Person Reporting',
    answer_type: 'text',
    required: true,
  },
  {
    section_id: 10,
    question_id: 'reporter_email',
    question: 'Email',
    answer_type: 'email-address',
    required: true,
  },
  {
    section_id: 10,
    question_id: 'designation_id',
    question: 'Designation',
    answer_type: 'dropdown',
    options: 'designations',
    required: true,
  },
  {
    section_id: 10,
    question_id: 'contact_number',
    question: 'Phone Number',
    answer_type: 'phone-pad',
    required: true,
  },
  {
    section_id: 10,
    question_id: 'reporter_date',
    question: 'Reporting date',
    answer_type: 'date',
    required: true,
  },
  {
    section_id: 10,
    section: 'Is the person submitting different from reporter?',
    question_id: 'person_submitting',
    question: 'Reporter different?',
    answer_type: 'radiobox',
    options: [
      {name: 'Yes', value: 'Yes'},
      {name: 'No', value: 'No'},
    ],
    required: true,
  },
  {
    section_id: 10,
    question_id: 'reporter_name_diff',
    question: 'Name',
    answer_type: 'text',
  },
  {
    section_id: 10,
    question_id: 'reporter_email_diff',
    question: 'Email Address',
    answer_type: 'email-address',
  },
  {
    section_id: 10,
    question_id: 'reporter_designation_diff',
    question: 'Designation',
    answer_type: 'dropdown',
    options: 'designations',
  },
  {
    section_id: 10,
    question_id: 'reporter_phone_diff',
    question: 'Phone Number',
    answer_type: 'phone-pad',
  },
  {
    section_id: 10,
    question_id: 'reporter_date_diff',
    question: 'Date',
    answer_type: 'date',
  },
];
