export const sadr = [
  {
    section_id: 1,
    question_id: 'report_title',
    question: 'Report Title',
    answer_type: 'text',
    search: 'dynamic',
    search_url: 'meddras',
    required: true,
  },
  {
    section_id: 1,
    section: 'The report is on *',
    question_id: 'report_sadr',
    question: 'Suspected adverse drug reaction ',
    answer_type: 'checkbox',
  },
  {
    section_id: 1,
    question_id: 'report_therapeutic',
    question: 'Suspected Therapeutic ineffectiveness',
    answer_type: 'checkbox',
  },
  {
    section_id: 1,
    question_id: 'report_misuse',
    question: 'Suspected misuse, abuse and / or dependence on medicines ',
    answer_type: 'checkbox',
  },
  {
    section_id: 1,
    question_id: 'report_off_label',
    question: 'Off-label Use',
    answer_type: 'checkbox',
  },

  {
    section_id: 1,
    section: 'Product category (Tick appropriate box) *',
    question_id: 'medicinal_product',
    question: 'Medicinal product ',
    answer_type: 'checkbox',
  },
  {
    section_id: 1,
    question_id: 'herbal_product',
    question: 'Herbal product',
    answer_type: 'checkbox',
  },
  {
    section_id: 1,
    question_id: 'cosmeceuticals',
    question: 'Cosmeceuticals',
    answer_type: 'checkbox',
  },
  {
    section_id: 1,
    question_id: 'product_other',
    question: 'Others ',
    answer_type: 'checkbox',
  },
  {
    section_id: 1,
    question_id: 'product_specify',
    question_linked: 'product_other',
    question: 'Others',
    answer_type: 'text',
  },
  {
    section_id: 2,
    question_id: 'name_of_institution',
    question: 'Name of institution',
    answer_type: 'text',
    search: 'institute',
    search_url: 'facility_codes',
    required: true,
  },
  {
    section_id: 2,
    question_id: 'institution_code',
    question: 'Institution Code',
    answer_type: 'text',
    search: 'institute',
    search_url: 'facility_codes',
  },
  {
    section_id: 2,
    question_id: 'address',
    question: 'Institution Address',
    answer_type: 'text',
    required: true,
  },
  {
    section_id: 2,
    question_id: 'contact',
    question: ' Institution Contact',
    answer_type: 'text',
  },
  {
    section_id: 2,
    question_id: 'county_id',
    question: 'County',
    answer_type: 'dropdown',
    options: 'counties',
    required: true,
  },
  {
    section_id: 2,
    question_id: 'sub_county_id',
    question_linked: 'county_id',
    question: 'Sub County',
    answer_type: 'dropdown',
    options: 'subcounties',
  },
  {
    section_id: 3,
    section: 'Patient Information',
    question_id: 'patient_name',
    question: "Patient's Initials",
    answer_type: 'text',
    required: true,
  },
  {
    section_id: 3,
    question_id: 'ip_no',
    question: 'IP/OP NO',
    answer_type: 'text',
  },
  {
    section_id: 3,
    question_id: 'date_of_birth',
    question: 'Date of Birth',
    answer_type: 'date',
    options: ['max'],
  },
  {
    section_id: 3,
    section: 'OR',
    question_id: 'age_group',
    question: 'Age Group',
    answer_type: 'dropdown',
    options: [
      { label: 'Select Age Group', value: '' },
      { label: 'neonate ( 0 - 1 month)', value: 'neonate' },
      { label: 'infant (1 month -1 year)', value: 'infant' },
      { label: 'child (1 - 11 years)', value: 'child' },
      { label: 'adolescent ( 12-17 years)', value: 'adolescent' },
      { label: 'adult (18-64 years)', value: 'adult' },
      { label: 'elderly (>65 years)', value: 'elderly' },
    ],
  },
  {
    section_id: 3,
    question_id: 'gender',
    question: 'Gender',
    answer_type: 'radiobox',
    options: [
      { name: 'Male', value: 'Male' },
      { name: 'Female', value: 'Female' }
    ],
    required: true,
  },
  {
    section_id: 3,
    question_id: 'pregnancy_status',
    question_linked: 'gender',
    answer_expect: 'Male',
    question: 'Pregnancy Status',
    answer_type: 'radiobox',
    options: [
      { name: 'Not Applicable', value: 'Not Applicable' },
      { name: 'Not pregnant', value: 'Not pregnant' },
      { name: '1st Trimester', value: '1st Trimester' },
      { name: '2nd Trimester', value: '2nd Trimester' },
      { name: '3rd Trimester', value: '3rd Trimester' },
    ],
  },
  {
    section_id: 3,
    question_id: 'patient_address',
    question: 'Patient Address',
    answer_type: 'text',
  },
  {
    section_id: 3,
    question_id: 'ward',
    question: 'Ward/Clinic (name/number)',
    answer_type: 'text',
  },
  {
    section_id: 3,
    question_id: 'known_allergy',
    question: 'Any Known Allergies?',
    answer_type: 'radiobox',
    options: [
      { name: 'Yes', value: 'Yes' },
      { name: 'No', value: 'No' },
    ],
    required: true,
  },
  {
    section_id: 3,
    question_id: 'known_allergy_specify',
    question_linked: 'known_allergy',
    question: 'Allergy',
    answer_type: 'text',
  },

  {
    section_id: 3,
    question_id: 'weight',
    question: 'Weight (Kg)',
    answer_type: 'numeric',
  },
  {
    section_id: 3,
    question_id: 'height',
    question: 'Height (cm)',
    answer_type: 'numeric',
  },
  {
    section_id: 4,
    question_id: 'diagnosis',
    question:
      'Diagnosis (What was the patient being treated for before getting the reaction)',
    answer_type: 'text',
  },
  {
    section_id: 4,
    question_id: 'date_of_onset_of_reaction',
    question: 'When did the reaction start? ',
    answer_type: 'date',
    options: ['max'],
    required: true,
  },
  {

    section_id: 4,
    question_id: 'reaction',
    question: 'Reaction',
    answer_type: 'text',
    search: 'dynamic',
    search_url: 'meddras',
    required: true,
  },
  {
    section_id: 4,
    question_id: 'description_of_reaction',
    question:
      'Brief description of reaction (Please describe the reaction in terms of symptoms)',
    answer_type: 'text',
    required: true,
  },
  {
    section_id: 4,
    question_id: 'Sadr-Other-Description',
    question: 'Other Description',
    answer_type: 'multitext',
    options: [{ question_id: 'description' }],
  },
  {
    section_id: 4,
    section: 'Please describe the reaction in terms of symptoms ',
    question_id: 'SadrDescription',
    question: 'Reaction symptoms',
    answer_type: 'multitext',
    options: [{ question_id: 'description' }],
  },
  {
    section_id: 4,
    question_id: 'medical_history',
    question:
      'Medical History(Other relevant history including pre-existing medical conditions e.g. allergies, smoking, alcohol use, hepatic/ renal dysfunction etc)',
    answer_type: 'text',
  },
  {
    section_id: 5,
    section:
      'List all medicines being currently used by the patient including OTC, and herbal products (* Tick the suspected medicine)',
    question_id: 'SadrListOfDrug',
    question_linked: 'date_of_onset_of_reaction',
    question: '',
    answer_type: 'table',
    required: true,
    headers: 1,
    options: [
      { 1: 'INN/Generic Name' },
      { 1: 'Brand Name' },
      { 1: 'Lot/Batch No.' },
      { 1: 'Manufacturer' },
      { 1: 'Dose' },
      { 1: 'Dose Quantity' },
      { 1: 'Route' },
      { 1: 'Frequency' },
      { 1: 'Treatment Start' },
      { 1: 'Treatment End' },
      { 1: 'Indication' },
      { 1: 'Suspected Drug(s) select at least one ✓ ' },
      { 1: 'Action' },
    ],
    table_form: [
      {
        order_id: 1,
        question_id: 'drug_name',
        question: 'INN/Generic Name(Include OTC and herbals)',
        answer_type: 'text',
        search: 'dynamic',
        search_url: 'drug_dictionaries',
        required: true,
      },
      {
        order_id: 2,
        question_id: 'brand_name',
        question: 'Brand Name',
        answer_type: 'text',
        search: 'dynamic',
        search_url: 'drug_dictionaries',
        required: true,
      },
      {
        order_id: 3,
        question_id: 'batch_no',
        question: 'Lot/Batch No.',
        answer_type: 'text',
      },
      {
        order_id: 4,
        question_id: 'manufacturer',
        question: 'Manufacturer',
        answer_type: 'text',
      },
      {
        order_id: 5,
        question_id: 'dose',
        question: 'Dose',
        answer_type: 'text',
        required: true,
      },
      {
        order_id: 6,
        question_id: 'dose_id',
        question: 'Dose Amount',
        answer_type: 'dropdown',
        options: 'doses',
        required: true,
      },
      {
        order_id: 7,
        question_id: 'route_id',
        question: 'Route',
        answer_type: 'dropdown',
        options: 'routes',
        required: true,
      },
      {
        order_id: 8,
        question_id: 'frequency_id',
        question: 'Frequency',
        answer_type: 'dropdown',
        options: 'frequencies',
        required: true,
      },
 

      {
        order_id: 9,
        question_id: 'start_date',
        question: 'Treatment Start Date',
        answer_type: 'date',
        options: ['max', 'date_of_onset_of_reaction'],
        required: true,
      },
      {
        order_id: 10,
        question_id: 'stop_date',
        question_linked: 'start_date',
        question: 'Treatment End Date',
        answer_type: 'date',
      },
      {
        order_id: 11,
        question_id: 'indication',
        question: 'Indication',
        answer_type: 'text',
      },
      {
        order_id: 12,
        section: 'Suspected drug(s)',
        question_id: 'suspected_drug',
        question: 'Suspected',
        answer_type: 'checkbox',
      },
    ],
  },
  {
    section_id: 6,
    section:
      'Past medication history (List all medicines used in the last 3 months including OTC, herbals, if pregnant indicate medicines used in the 1st trimester)',
    question_id: 'SadrListOfMedicine',
    question: '',
    answer_type: 'table',
    headers: 1,
    options: [
      { 1: 'INN/Generic Name' },
      { 1: 'Brand Name' },
      { 1: 'Lot/Batch No.' },
      { 1: 'Manufacturer' },
      { 1: 'Dose' },
      { 1: 'Dose Quantity' },
      { 1: 'Route' },
      { 1: 'Frequency' },
      { 1: 'Treatment Start' },
      { 1: 'Treatment End' },
      { 1: 'Indication' },
      { 1: 'Action' },
    ],
    table_form: [
      {
        order_id: 1,
        question_id: 'drug_name',
        question: 'INN/Generic Name(Include OTC and herbals)',
        answer_type: 'text',
        search: 'dynamic',
        search_url: 'drug_dictionaries',
        required: true,
      },
      {
        order_id: 2,
        question_id: 'brand_name',
        question: 'Brand Name',
        answer_type: 'text',
        search: 'dynamic',
        search_url: 'drug_dictionaries',
        required: true,
      },
      {
        order_id: 3,
        question_id: 'batch_no',
        question: 'Lot/Batch No.',
        answer_type: 'text',
      },
      {
        order_id: 4,
        question_id: 'manufacturer',
        question: 'Manufacturer',
        answer_type: 'text',
      },
      {
        order_id: 5,
        question_id: 'dose',
        question: 'Dose',
        answer_type: 'text',
        required: true,
      },
      {
        order_id: 6,
        question_id: 'dose_id',
        question: 'Dose Amount',
        answer_type: 'dropdown',
        options: 'doses',
        required: true,
      },
      {
        order_id: 7,
        question_id: 'route_id',
        question: 'Route',
        answer_type: 'dropdown',
        options: 'routes',
        required: true,
      },
      {
        order_id: 8,
        question_id: 'frequency_id',
        question: 'Frequency',
        answer_type: 'dropdown',
        options: 'frequencies',
        required: true,
      },
      {
        order_id: 9,
        question_id: 'start_date',
        question: 'Treatment Start Date',
        answer_type: 'date',
        options: ['max'],
        required: true,
      },
      {
        order_id: 10,
        question_id: 'stop_date',
        question_linked: 'start_date',
        question: 'Treatment End Date',
        answer_type: 'date',
      },
      {
        order_id: 11,
        question_id: 'indication',
        question: 'Indication',
        answer_type: 'text',
      },
    ],
  },
  {
    section_id: 7,
    section: 'Dechallenge/Rechallenge',
    question_id: 'reaction_resolve',
    question:
      'Did the reaction resolve after the drug was stopped or when the dose was reduced?',
    answer_type: 'radiobox',
    options: [
      { name: 'Yes', value: 'Yes' },
      { name: 'No', value: 'No' },
      { name: 'Unknown', value: 'Unknown' },
      { name: 'N/A', value: 'N/A' },
    ],
  },
  {
    section_id: 7,
    question_id: 'reaction_reappear',
    question: 'Did the reaction reappear after the drug was reintroduced?',
    answer_type: 'radiobox',
    options: [
      { name: 'Yes', value: 'Yes' },
      { name: 'No', value: 'No' },
      { name: 'Unknown', value: 'Unknown' },
      { name: 'N/A', value: 'N/A' },
    ],
  },
  {
    section_id: 7,
    question_id: 'lab_investigation',
    question: 'Any lab investigations and results',
    answer_type: 'text',
  },
  {
    section_id: 7,
    question_id: 'outcome',
    question: 'Outcome',
    answer_type: 'radiobox',
    options: [
      { name: 'Recovered/Resolved', value: 'Recovered/Resolved' },
      { name: 'Recovering/Resolving', value: 'Recovering/Resolving' },
      {
        name: 'Not recovered/Not resolved/Ongoing',
        value: 'Not recovered/Not resolved/Ongoing',
      },
      {
        name: 'Recovered/Resolved with sequelae',
        value: 'Recovered/Resolved with sequelae',
      },
      { name: 'Unknown', value: 'Unknown' },
      { name: 'Fatal', value: 'Fatal' },
    ],
    required: true,
  },
  {
    section_id: 8,
    section: 'Grading of the reaction /event',
    question_id: 'severity',
    question: 'Severity of reaction',
    answer_type: 'radiobox',
    options: [
      {
        name: 'Mild',
        value: 'Mild',
        info: 'The ADR requires no change in treatment with the suspected drug. \n\nThe ADR requires that the suspected drug be withheld, discontinued or otherwise changed. No antidote or other treatement is required. \n\nNo increase in length of stay.',
      },
      {
        name: 'Moderate',
        value: 'Moderate',
        info: 'The ADR requires that the suspected drug be withheld, discontinued or otherwise changed, and/or an antidote or other treatement is required. \n\nIncreases length of stay by at least one day. \n\nThe ADR is the reason for admission.',
      },
      {
        name: 'Severe',
        value: 'Severe',
        info: 'The ADR requires intensive medical care. \n\nThe ADR causes permanent harm to the patient',
      },
      {
        name: 'Fatal',
        value: 'Fatal',
        info: 'The ADR either directly or indirectly leads to the death of the patient',
      },
      { name: 'Unknown', value: 'Unknown' },
    ],
  },
  {
    section_id: 8,
    question_id: 'serious',
    question: 'Is the reaction serious ',
    answer_type: 'radiobox',
    options: [
      { name: 'Yes', value: 'Yes' },
      { name: 'No', value: 'No' },
    ],
    required: true,
  },
  {
    section_id: 8,
    question_id: 'serious_reason',
    question_linked: 'serious',
    question: 'Criteria/reason for seriousness',
    answer_type: 'radiobox',
    options: [
      {
        name: 'Hospitalization/ Prolonged Hospitalization',
        value: 'Hospitalization/ Prolonged Hospitalization',
      },
      { name: 'Disability', value: 'Disability' },
      { name: 'Congenital anomality', value: 'Congenital anomality' },
      { name: 'Life threatening', value: 'Life threatening' },
      { name: 'Death ', value: 'Death ' },
    ],
  },
  {
    section_id: 8,
    question_id: 'action_taken',
    question: 'Action taken ',
    answer_type: 'radiobox',
    options: [
      { name: 'Drug withdrawn', value: 'Drug withdrawn' },
      { name: 'Dose increased', value: 'Dose increased' },
      { name: 'Dose reduced', value: 'Dose reduced' },
      { name: 'Dose not changed', value: 'Dose not changed' },
      { name: 'Not applicable', value: 'Not applicable' },
      { name: 'Unknown', value: 'Unknown' },
    ],
    required: true,
  },
  {
    section_id: 8,
    question_id: 'any_other_comment',
    question: 'Any other comment',
    answer_type: 'text',
  },
  {
    section_id: 9,
    question_id: 'Attachment',
    question:
      'Do you have pictures or documents that you would like to send to PPB? click on the button to add them',
    answer_type: 'multiple_image',
    options: [
      { question_id: 'file' },
      { question_id: 'filename' },
      { question_id: 'description' },
    ],
  },
  {
    section_id: 9,
    section: 'Reporter Details',
    question_id: 'reporter_name',
    question: 'Name of Person Reporting',
    answer_type: 'text',
    required: true,
  },
  {
    section_id: 9,
    question_id: 'reporter_email',
    question: 'Email',
    answer_type: 'email-address',
    required: true,
  },
  {
    section_id: 9,
    question_id: 'designation_id',
    question: 'Designation',
    answer_type: 'dropdown',
    options: 'designations',
    required: true,
  },
  {
    section_id: 9,
    question_id: 'reporter_phone',
    question: 'Phone Number',
    answer_type: 'phone-pad',
    required: true,
  },
  {
    section_id: 9,
    question_id: 'reporter_date',
    question: 'Reporting date',
    answer_type: 'date',
    required: true,
  },

  {
    section_id: 9,
    section: 'Is the person submitting different from reporter?',
    question_id: 'person_submitting',
    question: 'Reporter different?',
    answer_type: 'radiobox',
    options: [
      { name: 'Yes', value: 'Yes' },
      { name: 'No', value: 'No' },
    ],
    required: true,
  },
  {
    section_id: 9,
    question_id: 'reporter_name_diff',
    question: 'Name',
    answer_type: 'text',
  },
  {
    section_id: 9,
    question_id: 'reporter_email_diff',
    question: 'Email Address',
    answer_type: 'email-address',
  },
  {
    section_id: 9,
    question_id: 'reporter_designation_diff',
    question: 'Designation',
    answer_type: 'dropdown',
    options: 'designations',
  },
  {
    section_id: 9,
    question_id: 'reporter_phone_diff',
    question: 'Phone Number',
    answer_type: 'phone-pad',
  },
  {
    section_id: 9,
    question_id: 'reporter_date_diff',
    question: 'Date',
    answer_type: 'date',
  },
];
